const flags = [
  {
    population: 38_000_145,
    capital: "Tashkent",
    code: "uz",
    continent: "Asia",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/uz.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/uz.svg",
    iso: true,
    name: "Uzbekistan",
  },
  {
    population: 38_000_145,
    capital: "Riyadh",
    code: "sa",
    continent: "Asia",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/sa.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/sa.svg",
    iso: true,
    name: "Kingdom of Saudi Arabia",
  },
  {
    population: 27_657_145,
    capital: "Kabul",
    code: "af",
    continent: "Asia",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/af.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/af.svg",
    iso: true,
    name: "Afghanistan",
  },
  {
    population: 30_000,
    capital: "Mariehamn",
    code: "ax",
    continent: "Europe",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/ax.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/ax.svg",
    iso: true,
    name: "Aland Islands",
  },
  {
    population: 2_886_026,
    capital: "Tirana",
    code: "al",
    continent: "Europe",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/al.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/al.svg",
    iso: true,
    name: "Albania",
  },
  {
    population: 40_400_000,
    capital: "Algiers",
    code: "dz",
    continent: "Africa",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/dz.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/dz.svg",
    iso: true,
    name: "Algeria",
  },
  {
    population: 46_029,
    capital: "Pago Pago",
    code: "as",
    continent: "Oceania",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/as.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/as.svg",
    iso: true,
    name: "American Samoa",
  },
  {
    population: 83_000,
    capital: "Andorra la Vella",
    code: "ad",
    continent: "Europe",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/ad.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/ad.svg",
    iso: true,
    name: "Andorra",
  },
  {
    population: 39_040_039,
    capital: "Luanda",
    code: "ao",
    continent: "Africa",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/ao.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/ao.svg",
    iso: true,
    name: "Angola",
  },
  {
    population: 14_728,
    capital: "The Valley",
    code: "ai",
    continent: "North America",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/ai.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/ai.svg",
    iso: true,
    name: "Anguilla",
  },
  {
    population: 27_500_000,
    capital: "Canberra",
    code: "au",
    continent: "Australia",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/au.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/au.svg",
    iso: true,
    name: "Australia",
  },
  {
    population: 206_135_893,
    capital: "Brazil",
    code: "br",
    continent: "South America",
    flag_1x1: "https://flagicons.lipis.dev/flags/1x1/br.svg",
    flag_4x3: "https://flagicons.lipis.dev/flags/4x3/br.svg",
    iso: true,
    name: "Brazil",
  },
];
